var Constants = Constants || {};
Constants.GET_TEACHERFILTER="GET_TEACHERFILTER"
Constants.SET_TEACHERFILTER="SET_TEACHERFILTER"

Constants.GET_COMBINATIONSUBJECTID="GET_COMBINATIONSUBJECTID"
Constants.SET_COMBINATIONSUBJECTID="SET_COMBINATIONSUBJECTID"

Constants.GET_TEACHERS="GET_TEACHERS"
Constants.SET_TEACHERS="SET_TEACHERS"

Constants.GET_ENTITY="GET_ENTITY"
Constants.SET_ENTITY="SET_ENTITY"

Constants.GET_COMBINATIONSUBJECT="GET_COMBINATIONSUBJECT"
Constants.SET_COMBINATIONSUBJECT="SET_COMBINATIONSUBJECT"

Constants.GET_FORMMODE="GET_FORMMODE"
Constants.SET_FORMMODE="SET_FORMMODE"

Constants.GET_TOGGLENAVBAR="GET_TOGGLENAVBAR"
Constants.SET_TOGGLENAVBAR="SET_TOGGLENAVBAR"

Constants.GET_TOGGLEMENU="GET_TOGGLEMENU"
Constants.SET_TOGGLEMENU="SET_TOGGLEMENU"

Constants.GET_SHOWEMPLOYEEDIALOG="GET_SHOWEMPLOYEEDIALOG"
Constants.SET_SHOWEMPLOYEEDIALOG="SET_SHOWEMPLOYEEDIALOG"

Constants.GET_SHOWCBDIALOG="GET_SHOWCBDIALOG"
Constants.SET_SHOWCBDIALOG="SET_SHOWCBDIALOG"

Constants.GET_MESSAGEWARNING="GET_MESSAGEWARNING"
Constants.SET_MESSAGEWARNING="SET_MESSAGEWARNING"

Constants.GET_MESSAGEDELETE="GET_MESSAGEDELETE"
Constants.SET_MESSAGEDELETE="SET_MESSAGEDELETE"

Constants.GET_LISTTEACHERID="GET_LISTTEACHERID"
Constants.SET_LISTTEACHERID="SET_LISTTEACHERID"

Constants.Login={
    Success:'SUCCESS',
    NotExists:'NOTEXISTS',
    Locked:'LOCKED'
}
export default Constants